baseURL = "https://mynewhugosite.com"
title = "Hugo training"
theme = "hugo-starter"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
